language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.1.1
  - jruby-19mode

before_install:
  - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra tidy
  - gem install rake minitest coderay stringex
  - (ruby --version | grep -qv 'ruby 1.8') && gem install prawn || true

script: ruby -rubygems -Ilib:test test/test_*
